version: "3"
services:
  wordpress:
    image: wordpress:5.2.0-php7.3-apache
    depends_on:
      - wordpress_db
    container_name: wordpress
    env_file:
      - .env
    restart: always 
    networks:
      - front
      - back
    volumes:
      - ./wp-content/plugins/wordcampmga:/var/www/html/wp-content/plugins/wordcampmga
      - ./wp-content/themes/wprig/:/var/www/html/wp-content/themes/wprig/
      - ./complete_install.sh:/tmp/complete_install.sh
      - ./package.json:/var/www/html/package.json

  wordpress_db:
    image: mariadb:latest
    container_name: wordpress_db
    env_file:
      - .env
    restart: always 
    networks:
      - back
    volumes:
      - ./mysql:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: wordpress_phpmyadmin
    env_file:
      - .env
    depends_on:
      - wordpress_db
    restart: always 
    networks:
      - back
    ports:
      - "8080:80"

  # https://github.com/mjstealey/wordpress-nginx-docker/blob/master/docker-compose.yml
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - '80:80'
    volumes:
      #- ./nginx/fastcgi.conf:/etc/nginx/fastcgi.conf
      - ./nginx/config/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/logs:/var/log/nginx
      - ./nginx/certs:/etc/letsencrypt
      - ./nginx/certs-data:/data/letsencrypt
    networks:
      - front
    depends_on:
      - wordpress
    restart: always

networks:
  front:
  back:
